spring.datasource.url=jdbc:postgresql://postgres:5432/coekipia
spring.datasource.username=coekipia
spring.datasource.password=coekipia
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
server.port=3003